Now the specs are broken due to the lack of implementation
As I try to increase the complexity of the first law specs I learned something new.
Crystal is a compiled language and when you try to implement a spec but classes are not declared or they do not have the necessary methods, you got errors like these:

```
Error in line 2: while requiring "./spec/conway_game_of_life_spec.cr"

in spec/conway_game_of_life_spec.cr:7: undefined constant ConwayGameOfLife::Population

        population = ConwayGameOfLife::Population.new
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error in line 2: while requiring "./spec/conway_game_of_life_spec.cr"

in spec/conway_game_of_life_spec.cr:9: undefined method 'alive!' for ConwayGameOfLife::Cell

        cell.alive!
```

They happen before the execution of the spec. It's a compile time error. So different from ruby which uses lazy evaluation.

In this commit I've added the basic understanding on how the generation should work. They are not passing because nothing was implemented.